CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255),
    description VARCHAR(255),
    due_date    DATE,
    status      VARCHAR(50),
    priority    VARCHAR(50),
    user_id     BIGINT,
    CONSTRAINT fk_tasks_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE subtasks
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255),
    status  VARCHAR(50),
    task_id BIGINT,
    CONSTRAINT fk_subtasks_tasks FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE TABLE attachments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255),
    file_type VARCHAR(255),
    file_url  VARCHAR(1024),
    task_id   BIGINT,
    CONSTRAINT fk_attachments_tasks FOREIGN KEY (task_id) REFERENCES tasks (id)
);
